// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel fireworks_prologue_cel000[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x0010
};

AnimationCel fireworks_prologue_cel001[] = {
    /* Len */ 1,
    /* 000 */ 0x0000, 0xc191, 0x1010
};

AnimationCel fireworks_prologue_cel002[] = {
    /* Len */ 2,
    /* 000 */ 0x0000, 0xc191, 0x1010,
    /* 001 */ 0x0000, 0xc030, 0x1000
};

AnimationCel fireworks_prologue_cel003[] = {
    /* Len */ 1,
    /* 000 */ 0x80c0, 0xc000, 0x1008
};

AnimationCel fireworks_prologue_cel004[] = {
    /* Len */ 1,
    /* 000 */ 0x00c0, 0xc000, 0x1008
};

