// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "fireworks_prologue_anim_cells.inc.c"

struct Animation anim_fireworks_prologue_title[] = {
    /* 000 */ { fireworks_prologue_cel001, 20 },
    /* 001 */ { fireworks_prologue_cel002, 60 },
    /* 002 */ { fireworks_prologue_cel000, 20 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_fireworks_prologue_unused[] = {
    /* 000 */ { fireworks_prologue_cel003, 20 },
    /* 001 */ { fireworks_prologue_cel004, 60 },
    /* 002 */ { fireworks_prologue_cel000, 20 },
    /* 003 */ END_ANIMATION,
};

