// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel bon_dance_prologue_cel000[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x00dd
};

AnimationCel bon_dance_prologue_cel001[] = {
    /* Len */ 4,
    /* 000 */ 0x00cb, 0x81b8, 0x002f,
    /* 001 */ 0x80cb, 0x81d8, 0x0033,
    /* 002 */ 0x40eb, 0x81b8, 0x00af,
    /* 003 */ 0x00eb, 0x41d8, 0x00b3
};

AnimationCel bon_dance_prologue_cel002[] = {
    /* Len */ 9,
    /* 000 */ 0x00cb, 0x81b8, 0x002f,
    /* 001 */ 0x80cb, 0x81d8, 0x0033,
    /* 002 */ 0x40eb, 0x81b8, 0x00af,
    /* 003 */ 0x00eb, 0x41d8, 0x00b3,
    /* 004 */ 0x00c3, 0x81e8, 0x0015,
    /* 005 */ 0x80c3, 0x8008, 0x0019,
    /* 006 */ 0x40e3, 0x81e8, 0x0095,
    /* 007 */ 0x00e3, 0x4008, 0x0099,
    /* 008 */ 0x40f3, 0x41f0, 0x00d6
};

AnimationCel bon_dance_prologue_cel003[] = {
    /* Len */ 2,
    /* 000 */ 0x00c0, 0xc1af, 0x0000,
    /* 001 */ 0x00c1, 0xc1dd, 0x0007
};

