// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "bunny_hop_prologue_anim_cells.inc.c"

struct Animation anim_bunny_hop_prologue_rabbits[] = {
    /* 000 */ { bunny_hop_prologue_cel000, 10 },
    /* 001 */ { bunny_hop_prologue_cel002, 10 },
    /* 002 */ { bunny_hop_prologue_cel003, 10 },
    /* 003 */ { bunny_hop_prologue_cel004, 10 },
    /* 004 */ { bunny_hop_prologue_cel005, 10 },
    /* 005 */ { bunny_hop_prologue_cel006, 60 },
    /* 006 */ END_ANIMATION,
};

struct Animation anim_bunny_hop_prologue_title[] = {
    /* 000 */ { bunny_hop_prologue_cel000, 10 },
    /* 001 */ { bunny_hop_prologue_cel000, 10 },
    /* 002 */ { bunny_hop_prologue_cel007, 20 },
    /* 003 */ { bunny_hop_prologue_cel009, 20 },
    /* 004 */ { bunny_hop_prologue_cel009, 100 },
    /* 005 */ END_ANIMATION,
};

