// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "sneaky_spirits_2_prologue_anim_cells.inc.c"

struct Animation anim_sneaky_spirits_2_prologue_title[] = {
    /* 000 */ { sneaky_spirits_2_prologue_cel000, 20 },
    /* 001 */ { sneaky_spirits_2_prologue_cel001, 20 },
    /* 002 */ { sneaky_spirits_2_prologue_cel002, 40 },
    /* 003 */ { sneaky_spirits_2_prologue_cel004, 20 },
    /* 004 */ { sneaky_spirits_2_prologue_cel005, 20 },
    /* 005 */ { sneaky_spirits_2_prologue_cel006, 20 },
    /* 006 */ { sneaky_spirits_2_prologue_cel006, 40 },
    /* 007 */ { sneaky_spirits_2_prologue_cel000, 60 },
    /* 008 */ END_ANIMATION,
};

