// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel rat_race_prologue_cel000[] = {
    /* Len */ 2,
    /* 000 */ 0x40f0, 0x81c0, 0x0118,
    /* 001 */ 0x40f0, 0x81e0, 0x011c
};

AnimationCel rat_race_prologue_cel001[] = {
    /* Len */ 1,
    /* 000 */ 0x40e0, 0xc1b0, 0x0118
};

AnimationCel rat_race_prologue_cel002[] = {
    /* Len */ 5,
    /* 000 */ 0x40d8, 0xc1a3, 0x0110,
    /* 001 */ 0x80d8, 0x41e3, 0x018e,
    /* 002 */ 0x40f8, 0x41a3, 0x01ef,
    /* 003 */ 0x40f8, 0x41c3, 0x01db,
    /* 004 */ 0x00f8, 0x01e3, 0x019f
};

AnimationCel rat_race_prologue_cel003[] = {
    /* Len */ 5,
    /* 000 */ 0x00b8, 0xc1a0, 0x0010,
    /* 001 */ 0x80b8, 0xc1e0, 0x0018,
    /* 002 */ 0x40f8, 0x41a0, 0x01cf,
    /* 003 */ 0x40f8, 0x41c0, 0x01d7,
    /* 004 */ 0x40f8, 0x41e0, 0x01d3
};

AnimationCel rat_race_prologue_cel004[] = {
    /* Len */ 4,
    /* 000 */ 0x00a8, 0xc19d, 0x0000,
    /* 001 */ 0x40e0, 0xc1ad, 0x0108,
    /* 002 */ 0x00d8, 0x01e5, 0x019d,
    /* 003 */ 0x00e0, 0x81e5, 0x001c
};

AnimationCel rat_race_prologue_cel005[] = {
    /* Len */ 5,
    /* 000 */ 0x00a0, 0xc19d, 0x0008,
    /* 001 */ 0x40e0, 0xc1a6, 0x0100,
    /* 002 */ 0x00e0, 0x81e6, 0x009c,
    /* 003 */ 0x80c0, 0x81e6, 0x018c,
    /* 004 */ 0x00d8, 0x01dd, 0x01bd
};

AnimationCel rat_race_prologue_cel006[] = {
    /* Len */ 1,
    /* 000 */ 0x0000, 0x81b0, 0x0184
};

AnimationCel rat_race_prologue_cel007[] = {
    /* Len */ 2,
    /* 000 */ 0x0000, 0x81b0, 0x0184,
    /* 001 */ 0x0000, 0x81ce, 0x0188
};

AnimationCel rat_race_prologue_cel008[] = {
    /* Len */ 3,
    /* 000 */ 0x0001, 0x81ee, 0x0180,
    /* 001 */ 0x0000, 0x81b0, 0x0184,
    /* 002 */ 0x0000, 0x81ce, 0x0188
};

AnimationCel rat_race_prologue_cel009[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x019e
};

AnimationCel rat_race_prologue_cel010[] = {
    /* Len */ 3,
    /* 000 */ 0x4003, 0x800c, 0x018f,
    /* 001 */ 0x4003, 0x802c, 0x0193,
    /* 002 */ 0x0003, 0x404c, 0x0197
};

AnimationCel rat_race_prologue_cel011[] = {
    /* Len */ 3,
    /* 000 */ 0x4003, 0x800c, 0x218f,
    /* 001 */ 0x4003, 0x802c, 0x2193,
    /* 002 */ 0x0003, 0x404c, 0x2197
};

AnimationCel rat_race_prologue_cel012[] = {
    /* Len */ 3,
    /* 000 */ 0x4003, 0x800c, 0x318f,
    /* 001 */ 0x4003, 0x802c, 0x3193,
    /* 002 */ 0x0003, 0x404c, 0x3197
};

AnimationCel rat_race_prologue_cel013[] = {
    /* Len */ 3,
    /* 000 */ 0x4003, 0x800c, 0x418f,
    /* 001 */ 0x4003, 0x802c, 0x4193,
    /* 002 */ 0x0003, 0x404c, 0x4197
};

AnimationCel rat_race_prologue_cel014[] = {
    /* Len */ 3,
    /* 000 */ 0x4003, 0x800c, 0x518f,
    /* 001 */ 0x4003, 0x802c, 0x5193,
    /* 002 */ 0x0003, 0x404c, 0x5197
};

AnimationCel rat_race_prologue_cel015[] = {
    /* Len */ 3,
    /* 000 */ 0x4003, 0x800c, 0x618f,
    /* 001 */ 0x4003, 0x802c, 0x6193,
    /* 002 */ 0x0003, 0x404c, 0x6197
};

