// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel rhythm_tweezers_2_prologue_cel000[] = {
    /* Len */ 2,
    /* 000 */ 0x40e0, 0xc1cc, 0x0000,
    /* 001 */ 0x00e0, 0x800c, 0x0008
};

AnimationCel rhythm_tweezers_2_prologue_cel001[] = {
    /* Len */ 2,
    /* 000 */ 0x40e0, 0xc1cc, 0x1000,
    /* 001 */ 0x00e0, 0x800c, 0x1008
};

AnimationCel rhythm_tweezers_2_prologue_cel002[] = {
    /* Len */ 2,
    /* 000 */ 0x40e0, 0xc1cc, 0x2000,
    /* 001 */ 0x00e0, 0x800c, 0x2008
};

AnimationCel rhythm_tweezers_2_prologue_cel003[] = {
    /* Len */ 2,
    /* 000 */ 0x40e0, 0xc1cc, 0x3000,
    /* 001 */ 0x00e0, 0x800c, 0x3008
};

AnimationCel rhythm_tweezers_2_prologue_cel004[] = {
    /* Len */ 2,
    /* 000 */ 0x40e0, 0xc1cc, 0x4000,
    /* 001 */ 0x00e0, 0x800c, 0x4008
};

