// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel rhythm_tweezers_prologue_cel004[] = {
    /* Len */ 2,
    /* 000 */ 0x40e0, 0xc1d4, 0x4000,
    /* 001 */ 0x80e0, 0x8014, 0x4008
};

AnimationCel rhythm_tweezers_prologue_cel001[] = {
    /* Len */ 2,
    /* 000 */ 0x40e0, 0xc1d4, 0x1000,
    /* 001 */ 0x80e0, 0x8014, 0x1008
};

AnimationCel rhythm_tweezers_prologue_cel008[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x100a,
    /* 001 */ 0x4000, 0x8020, 0x100e
};

AnimationCel rhythm_tweezers_prologue_cel000[] = {
    /* Len */ 2,
    /* 000 */ 0x40e0, 0xc1d4, 0x0000,
    /* 001 */ 0x80e0, 0x8014, 0x0008
};

AnimationCel rhythm_tweezers_prologue_cel009[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x000a,
    /* 001 */ 0x4000, 0x8020, 0x000e
};

AnimationCel rhythm_tweezers_prologue_cel007[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x200a,
    /* 001 */ 0x4000, 0x8020, 0x200e
};

AnimationCel rhythm_tweezers_prologue_cel006[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x300a,
    /* 001 */ 0x4000, 0x8020, 0x300e
};

AnimationCel rhythm_tweezers_prologue_cel002[] = {
    /* Len */ 2,
    /* 000 */ 0x40e0, 0xc1d4, 0x2000,
    /* 001 */ 0x80e0, 0x8014, 0x2008
};

AnimationCel rhythm_tweezers_prologue_cel005[] = {
    /* Len */ 2,
    /* 000 */ 0x4000, 0x8000, 0x400a,
    /* 001 */ 0x4000, 0x8020, 0x400e
};

AnimationCel rhythm_tweezers_prologue_cel003[] = {
    /* Len */ 2,
    /* 000 */ 0x40e0, 0xc1d4, 0x3000,
    /* 001 */ 0x80e0, 0x8014, 0x3008
};

