.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Basic 2) - Script Entry Point

script script_drum_lesson_basic_2_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_basic_2_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_basic_2, script_drum_lesson_basic_2_entry



.section .rodata
@ Drum Lesson (Basic 2) - Data

text D_08061998
    .asciz "仔细听好再照着做哦。\n想什么时候开始都可以。\n停下演奏的话，\n还能再听一遍示范哦！"
endtext


script D_080619f0
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
return


script D_08061a44
    spawn_cue CUE_KICK_R
    rest 21
return


text D_08061a68
    .asciz "有一处会换音哦！\n听得出来吗？"
endtext


script D_08061a90
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08061ae4
    .asciz "还会再换一处音哦！\n听得出来吗？"
endtext


script D_08061b10
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08061b64
    .asciz "这次会多一个音哦！\n听得出来吗？"
endtext


script D_08061b94
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08061c00
    .asciz "还会再多一个音哦！\n听得出来吗？"
endtext


script D_08061c2c
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_KICK_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08061cb0
    .asciz "又会再多一个音哦！\n听得出来吗？"
endtext


script D_08061cdc
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 9
return


text D_08061d18
    .asciz "这次要用底鼓和军鼓\n这两种鼓来上课。"
endtext


text D_08061d70
    .asciz "按 B 键或十字键下，\n都可以敲底鼓哦！"
endtext


text D_08061dbc
    .asciz "你应该已经知道了，\n军鼓是用 A 键和\n十字键左来敲的。"
endtext


text D_08061e04
    .asciz "好，那就差不多开始吧〜"
endtext



.section .script.main
@ Drum Lesson (Basic 2) - Tables

struct D_08a42504
    .word D_08061a44
    .word D_080619f0
    .word s_hakushu_solo_seqData
    .word D_08061998
endstruct

struct D_08a42514
    .word D_08061a44
    .word D_08061a90
    .word s_hakushu_solo_seqData
    .word D_08061a68
endstruct

struct D_08a42524
    .word D_08061a44
    .word D_08061b10
    .word s_warai_little_seqData
    .word D_08061ae4
endstruct

struct D_08a42534
    .word D_08061a44
    .word D_08061b94
    .word s_warai_seqData
    .word D_08061b64
endstruct

struct D_08a42544
    .word D_08061a44
    .word D_08061c2c
    .word s_kansei_solo_seqData
    .word D_08061c00
endstruct

struct D_08a42554
    .word D_08061cdc
    .word D_08061c2c
    .word s_kansei_seqData
    .word D_08061cb0
endstruct



@ Drum Lesson (Basic 2) - Main Script

script script_drum_lesson_basic_2_main
    set_tempo 116
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 4
    dms_event09 1
    rest 24
    rest 24
    dms_event02 TRUE
    rest 24
    dms_set_dialogue_text D_08061d18
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061d70
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061dbc
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061e04
    rest 12
    dms_event15
    dms_event16
    rest 12
    rest 24
    run drum_lesson_script_import_pattern, D_08a42504
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42514
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42524
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42534
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42544
    call drum_lessons_sub_08a7d7a0
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a42554
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
