.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Short 8) - Script Entry Point

script script_drum_lesson_short_8_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_short_8_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_short_8, script_drum_lesson_short_8_entry



.section .rodata
@ Drum Lesson (Short 8) - Data

text D_0805fa78
    .asciz "仔细听好再照着做哦。\n想什么时候开始都可以。\n停下演奏的话，\n还能再听一遍示范哦！"
endtext


script D_0805fad0
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


script D_0805fb3c
    spawn_cue CUE_KICK_R
    rest 21
return


text D_0805fb60
    .asciz "有一处会多一个音哦！\n听得出来吗？\n提示：双手一起"
endtext


script D_0805fb94
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 11
    spawn_cue CUE_SNARE_R
    rest 1
    rest 1
    spawn_cue CUE_SNARE_L
    rest 23
return


text D_0805fc24
    .asciz "还会再多一处哦！\n听得出来吗？"
endtext


script D_0805fc54
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 9
return


text D_0805fc90
    .asciz "又会再多一处哦！\n听得出来吗？"
endtext


script D_0805fcc0
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 3
return


text D_0805fd14
    .asciz "然后居然又多一处哦！\n听得出来吗？"
endtext


script D_0805fd50
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 4
    spawn_cue CUE_KICK_L
    rest 4
    spawn_cue CUE_KICK_R
    rest 1
return


text D_0805fdbc
    .asciz "这回居然也多一处哦！\n听得出来吗？"
endtext


script D_0805fdf8
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 18
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 11
    spawn_cue CUE_SNARE_R
    rest 1
    rest 1
    spawn_cue CUE_SNARE_L
    rest 23
return



.section .script.main
@ Drum Lesson (Short 8) - Tables

struct D_08a41530
    .word D_0805fb3c
    .word D_0805fad0
    .word s_hakushu_solo_seqData
    .word D_0805fa78
endstruct

struct D_08a41540
    .word D_0805fb3c
    .word D_0805fb94
    .word s_hakushu_solo_seqData
    .word D_0805fb60
endstruct

struct D_08a41550
    .word D_0805fc54
    .word D_0805fb94
    .word s_warai_little_seqData
    .word D_0805fc24
endstruct

struct D_08a41560
    .word D_0805fcc0
    .word D_0805fb94
    .word s_warai_seqData
    .word D_0805fc90
endstruct

struct D_08a41570
    .word D_0805fd50
    .word D_0805fb94
    .word s_kansei_solo_seqData
    .word D_0805fd14
endstruct

struct D_08a41580
    .word D_0805fd50
    .word D_0805fdf8
    .word s_kansei_seqData
    .word D_0805fdbc
endstruct



@ Drum Lesson (Short 8) - Main Script

script script_drum_lesson_short_8_main
    set_tempo 116
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 4
    dms_event09 1
    rest 24
    dms_event02 TRUE
    run drum_lesson_script_import_pattern, D_08a41530
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41540
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41550
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41560
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41570
    call drum_lessons_sub_08a7d7a0
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a41580
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
