.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Short 1) - Script Entry Point

script script_drum_lesson_short_1_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_short_1_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_short_1, script_drum_lesson_short_1_entry



.section .rodata
@ Drum Lesson (Short 1) - Data

text D_0805f114
    .asciz "仔细听好再照着做哦。\n想什么时候开始都可以。\n停下演奏的话，\n还能再听一遍示范哦！"
endtext


script D_0805f16c
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
return


script D_0805f1c0
    spawn_cue CUE_KICK_R
    rest 21
return


text D_0805f1e4
    .asciz "有一处会多一个音哦！\n听得出来吗？"
endtext


script D_0805f20c
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_0805f278
    .asciz "还会再多一处哦！\n听得出来吗？"
endtext


script D_0805f2a8
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_0805f32c
    .asciz "又会再多一处哦！\n听得出来吗？"
endtext


script D_0805f35c
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
return


text D_0805f3f8
    .asciz "然后居然又多一处哦！\n听得出来吗？"
endtext


script D_0805f434
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 9
return


text D_0805f470
    .asciz "这回居然也多一处哦！\n听得出来吗？"
endtext


script D_0805f4ac
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_SNARE_R
    rest 12
return



.section .script.main
@ Drum Lesson (Short 1) - Tables

struct D_08a41068
    .word D_0805f1c0
    .word D_0805f16c
    .word s_hakushu_solo_seqData
    .word D_0805f114
endstruct

struct D_08a41078
    .word D_0805f1c0
    .word D_0805f20c
    .word s_hakushu_solo_seqData
    .word D_0805f1e4
endstruct

struct D_08a41088
    .word D_0805f1c0
    .word D_0805f2a8
    .word s_warai_little_seqData
    .word D_0805f278
endstruct

struct D_08a41098
    .word D_0805f1c0
    .word D_0805f35c
    .word s_warai_seqData
    .word D_0805f32c
endstruct

struct D_08a410a8
    .word D_0805f434
    .word D_0805f35c
    .word s_kansei_solo_seqData
    .word D_0805f3f8
endstruct

struct D_08a410b8
    .word D_0805f434
    .word D_0805f4ac
    .word s_kansei_seqData
    .word D_0805f470
endstruct



@ Drum Lesson (Short 1) - Main Script

script script_drum_lesson_short_1_main
    set_tempo 116
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 4
    dms_event09 1
    rest 24
    dms_event02 TRUE
    run drum_lesson_script_import_pattern, D_08a41068
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41078
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41088
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41098
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a410a8
    call drum_lessons_sub_08a7d7a0
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a410b8
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
