.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Basic 1) - Script Entry Point

script script_drum_lesson_basic_1_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_basic_1_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_basic_1, script_drum_lesson_basic_1_entry



.section .rodata
@ Drum Lesson (Basic 1) - Data

text D_080613e4
    .asciz "仔细听好再照着做哦。\n想什么时候开始都可以。\n停下演奏的话，\n还能再听一遍示范哦！"
endtext


script D_0806143c
    spawn_cue CUE_SNARE_R
    rest 24
    spawn_cue CUE_SNARE_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_R
    rest 24
return


script D_080614a8
    spawn_cue CUE_SNARE_R
    rest 21
return


text D_080614cc
    .asciz "有一处会多一个音哦！\n听得出来吗？"
endtext


script D_080614f4
    spawn_cue CUE_SNARE_R
    rest 24
    spawn_cue CUE_SNARE_R
    rest 12
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_SNARE_R
    rest 24
return


text D_08061578
    .asciz "还会再多一处哦！\n听得出来吗？"
endtext


script D_080615a8
    spawn_cue CUE_SNARE_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 9
return


text D_080615e4
    .asciz "又会再多一处哦！\n听得出来吗？"
endtext


script D_08061614
    spawn_cue CUE_SNARE_R
    rest 24
    spawn_cue CUE_SNARE_R
    rest 12
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_SNARE_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
return


script D_080616b0
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_SNARE_R
    rest 9
return


text D_08061704
    .asciz "这次来试着敲一种叫军鼓的鼓吧。"
endtext


text D_08061740
    .asciz "按 A 键或十字键左，\n都可以敲军鼓哦！"
endtext


text D_0806178c
    .asciz "那么，马上开始上课吧！\n"
endtext


text D_080617bc
    .asciz "上面亮着的那排灯，\n就是时机提示灯。"
endtext


text D_080617f0
    .asciz "中间的绿色就是正好！\n偏左就是抢拍，\n偏右就是慢了。"
endtext


text D_0806183c
    .asciz "要是总是打不准，\n就看看上面的灯，\n确认自己偏到哪边了哦！"
endtext


text D_08061884
    .asciz "好，接着下一段！"
endtext


text D_0806189c
    .asciz "要是觉得演奏太快，\n就按一下 START 键！\n这样的话…"
endtext


text D_080618d8
    .asciz "演奏就会慢下来哦！\n可以拿来参考看看。"
endtext


text D_08061910
    .asciz "想回到原来的速度，\n再按一次 START 键就行。"
endtext


text D_08061950
    .asciz "顺带一提，慢速播放时\n课程是不会往下推进的。"
endtext


text D_08061980
    .asciz "好，继续下一段吧！"
endtext



.section .script.main
@ Drum Lesson (Basic 1) - Tables

struct D_08a41e90
    .word D_080614a8
    .word D_0806143c
    .word s_hakushu_solo_seqData
    .word D_080613e4
endstruct

struct D_08a41ea0
    .word D_080614a8
    .word D_080614f4
    .word s_hakushu_solo_seqData
    .word D_080614cc
endstruct

struct D_08a41eb0
    .word D_080615a8
    .word D_080614f4
    .word s_warai_little_seqData
    .word D_08061578
endstruct

struct D_08a41ec0
    .word D_080615a8
    .word D_08061614
    .word s_warai_seqData
    .word D_080615e4
endstruct

struct D_08a41ed0
    .word D_080616b0
    .word D_08061614
    .word s_kansei_solo_seqData
    .word D_080614cc
endstruct



@ Drum Lesson (Basic 1) - Main Script

script script_drum_lesson_basic_1_main
    set_tempo 116
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 4
    dms_event09 1
    rest 24
    rest 24
    dms_event02 TRUE
    rest 24
    dms_set_dialogue_text D_08061704
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061740
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_0806178c
    rest 12
    dms_event15
    dms_event16
    rest 12
    rest 24
    run drum_lesson_script_import_pattern, D_08a41e90
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41ea0
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_dialogue_text D_080617bc
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_080617f0
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_0806183c
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061884
    rest 12
    dms_event15
    dms_event16
    rest 12
    run drum_lesson_script_import_pattern, D_08a41eb0
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41ec0
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_dialogue_text D_0806189c
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_080618d8
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061910
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061950
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061980
    rest 12
    dms_event15
    dms_event16
    rest 12
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a41ed0
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
