"""Explain imported text at file level and mark unreviewed source entries.

This script is idempotent: it inserts only absent comments. It does not edit
translations or code logic, and it leaves unsafe conditional entries in the
searchable TODO index generated by pipeline.py.
"""

from collections import defaultdict
import csv
from pathlib import Path
import re

from pipeline import ROOT, TABLE, atomic_text, locate

HEADER_C = (
    '/* 中文文本：本文件采用译文包中 stage 5 的已校对条目。\n'
    ' * 字符串中的 \\n 是游戏画面换行；相邻引号只是方便阅读源码。\n'
    ' * 未校对或未定位的条目见 text/zh_hans/TODO_未校对.md。 */\n'
)
HEADER_BS = (
    '@ 中文文本：本文件采用译文包中 stage 5 的已校对条目。\n'
    '@ 字符串中的 \\n 是游戏画面换行；未校对项见 text/zh_hans/TODO_未校对.md。\n'
)


def group_index(row, siblings, groups):
    ordered = sorted(siblings, key=lambda item: int(match.group(1))
                     if (match := re.search(r'\[(\d+)\]$', item['key'])) else -1)
    if len(groups) == len(ordered):
        return ordered.index(row)
    indexes = [re.search(r'\[(\d+)\]$', item['key']) for item in ordered]
    if all(indexes) and max(int(match.group(1)) for match in indexes) < len(groups):
        return int(re.search(r'\[(\d+)\]$', row['key']).group(1))
    return None


def main():
    with TABLE.open(encoding='utf-8', newline='') as stream:
        rows = list(csv.DictReader(stream, delimiter='\t'))
    by_file = defaultdict(list)
    for row in rows:
        by_file[row['file']].append(row)
    headers = todos = unsafe = 0
    for name, members in by_file.items():
        path = ROOT / name
        if path.suffix not in ('.c', '.bs') or not path.exists():
            continue
        text = path.read_text(encoding='utf-8')
        siblings = defaultdict(list)
        for row in members:
            siblings[row['key'].split('[', 1)[0]].append(row)
        edits = []
        for row in members:
            if row['status'] == 'final':
                continue
            key = row['key']
            if f'TODO 未校对：{key}' in text:
                continue
            groups = locate(text, path, key)
            index = group_index(row, siblings[key.split('[', 1)[0]], groups) if groups else None
            if index is None or groups[index] is None:
                unsafe += 1
                continue
            start, _, _ = groups[index]
            line_start = text.rfind('\n', 0, start) + 1
            indent = re.match(r'[ \t]*', text[line_start:start]).group()
            marker = '@' if path.suffix == '.bs' else '//'
            explanation = f'{indent}{marker} TODO 未校对：{key} 译文包未到 stage 5，暂留原文。\n'
            edits.append((line_start, explanation))
        if edits:
            for at, comment in sorted(edits, reverse=True):
                text = text[:at] + comment + text[at:]
            todos += len(edits)
        header = HEADER_BS if path.suffix == '.bs' else HEADER_C
        if any(row['status'] == 'final' and not row['note'] for row in members) and not text.startswith(header):
            text = header + text
            headers += 1
        if edits or (text != path.read_text(encoding='utf-8')):
            atomic_text(path, text)
    print(f'commented files={headers}, inline TODO={todos}, index-only TODO={unsafe}')


if __name__ == '__main__':
    main()
