// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "rap_men_prologue_anim_cells.inc.c"

struct Animation anim_rap_men_prologue_title[] = {
    /* 000 */ { rap_men_prologue_cel000, 100 },
    /* 001 */ { rap_men_prologue_cel001, 6 },
    /* 002 */ { rap_men_prologue_cel002, 6 },
    /* 003 */ { rap_men_prologue_cel003, 6 },
    /* 004 */ { rap_men_prologue_cel004, 6 },
    /* 005 */ { rap_men_prologue_cel003, 6 },
    /* 006 */ { rap_men_prologue_cel002, 6 },
    /* 007 */ { rap_men_prologue_cel007, 6 },
    /* 008 */ { rap_men_prologue_cel008, 6 },
    /* 009 */ { rap_men_prologue_cel000, 100 },
    /* 010 */ END_ANIMATION,
};

