// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "cosmic_dance_prologue_anim_cells.inc.c"

struct Animation anim_cosmic_dance_prologue_title[] = {
    /* 000 */ { cosmic_dance_prologue_cel000, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_cosmic_dance_prologue_dancer[] = {
    /* 000 */ { cosmic_dance_prologue_cel001, 4 },
    /* 001 */ END_ANIMATION,
};

