// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel cosmic_dance_prologue_cel000[] = {
    /* Len */ 4,
    /* 000 */ 0x80ea, 0x81dc, 0x0008,
    /* 001 */ 0x80ea, 0x81ec, 0x000a,
    /* 002 */ 0x80ea, 0x8004, 0x000c,
    /* 003 */ 0x80ea, 0x8014, 0x000e
};

AnimationCel cosmic_dance_prologue_cel001[] = {
    /* Len */ 1,
    /* 000 */ 0x00e0, 0xc1e0, 0x0000
};

