// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "space_dance_prologue_anim_cells.inc.c"

struct Animation anim_space_dance_prologue_title[] = {
    /* 000 */ { space_dance_prologue_cel000, 1 },
    /* 001 */ { space_dance_prologue_cel001, 1 },
    /* 002 */ { space_dance_prologue_cel002, 4 },
    /* 003 */ { space_dance_prologue_cel001, 1 },
    /* 004 */ { space_dance_prologue_cel000, 1 },
    /* 005 */ { space_dance_prologue_cel003, 1 },
    /* 006 */ { space_dance_prologue_cel004, 1 },
    /* 007 */ { space_dance_prologue_cel005, 1 },
    /* 008 */ { space_dance_prologue_cel006, 1 },
    /* 009 */ { space_dance_prologue_cel007, 10 },
    /* 010 */ { space_dance_prologue_cel008, 1 },
    /* 011 */ { space_dance_prologue_cel009, 1 },
    /* 012 */ { space_dance_prologue_cel010, 4 },
    /* 013 */ { space_dance_prologue_cel009, 1 },
    /* 014 */ { space_dance_prologue_cel008, 1 },
    /* 015 */ { space_dance_prologue_cel011, 1 },
    /* 016 */ { space_dance_prologue_cel012, 1 },
    /* 017 */ { space_dance_prologue_cel013, 1 },
    /* 018 */ { space_dance_prologue_cel014, 1 },
    /* 019 */ { space_dance_prologue_cel015, 10 },
    /* 020 */ { space_dance_prologue_cel016, 1 },
    /* 021 */ { space_dance_prologue_cel017, 1 },
    /* 022 */ { space_dance_prologue_cel018, 4 },
    /* 023 */ { space_dance_prologue_cel017, 1 },
    /* 024 */ { space_dance_prologue_cel016, 1 },
    /* 025 */ { space_dance_prologue_cel019, 1 },
    /* 026 */ { space_dance_prologue_cel020, 1 },
    /* 027 */ { space_dance_prologue_cel021, 1 },
    /* 028 */ { space_dance_prologue_cel022, 1 },
    /* 029 */ { space_dance_prologue_cel023, 10 },
    /* 030 */ { space_dance_prologue_cel024, 1 },
    /* 031 */ { space_dance_prologue_cel025, 1 },
    /* 032 */ { space_dance_prologue_cel026, 4 },
    /* 033 */ { space_dance_prologue_cel025, 1 },
    /* 034 */ { space_dance_prologue_cel024, 1 },
    /* 035 */ { space_dance_prologue_cel027, 1 },
    /* 036 */ { space_dance_prologue_cel028, 1 },
    /* 037 */ { space_dance_prologue_cel029, 1 },
    /* 038 */ { space_dance_prologue_cel030, 1 },
    /* 039 */ { space_dance_prologue_cel031, 10 },
    /* 040 */ { space_dance_prologue_cel032, 1 },
    /* 041 */ { space_dance_prologue_cel033, 1 },
    /* 042 */ { space_dance_prologue_cel034, 4 },
    /* 043 */ { space_dance_prologue_cel033, 1 },
    /* 044 */ { space_dance_prologue_cel032, 1 },
    /* 045 */ { space_dance_prologue_cel035, 1 },
    /* 046 */ { space_dance_prologue_cel036, 1 },
    /* 047 */ { space_dance_prologue_cel037, 1 },
    /* 048 */ { space_dance_prologue_cel038, 1 },
    /* 049 */ { space_dance_prologue_cel039, 213 },
    /* 050 */ END_ANIMATION,
};

struct Animation anim_space_dance_prologue_star[] = {
    /* 000 */ { space_dance_prologue_cel080, 6 },
    /* 001 */ { space_dance_prologue_cel081, 6 },
    /* 002 */ { space_dance_prologue_cel082, 6 },
    /* 003 */ { space_dance_prologue_cel083, 6 },
    /* 004 */ { space_dance_prologue_cel084, 20 },
    /* 005 */ END_ANIMATION,
};

struct Animation anim_space_dance_prologue_faces[] = {
    /* 000 */ { space_dance_prologue_cel084, 220 },
    /* 001 */ { space_dance_prologue_cel085, 90 },
    /* 002 */ END_ANIMATION,
};

