// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "sick_beats_prologue_anim_cells.inc.c"

struct Animation anim_sick_beats_prologue_virus[] = {
    /* 000 */ { sick_beats_prologue_cel000, 20 },
    /* 001 */ { sick_beats_prologue_cel001, 4 },
    /* 002 */ { sick_beats_prologue_cel002, 4 },
    /* 003 */ { sick_beats_prologue_cel003, 4 },
    /* 004 */ { sick_beats_prologue_cel004, 4 },
    /* 005 */ { sick_beats_prologue_cel005, 4 },
    /* 006 */ { sick_beats_prologue_cel006, 60 },
    /* 007 */ END_ANIMATION,
};

struct Animation anim_sick_beats_prologue_title[] = {
    /* 000 */ { sick_beats_prologue_cel000, 60 },
    /* 001 */ { sick_beats_prologue_cel016, 4 },
    /* 002 */ { sick_beats_prologue_cel017, 4 },
    /* 003 */ { sick_beats_prologue_cel018, 4 },
    /* 004 */ { sick_beats_prologue_cel019, 4 },
    /* 005 */ { sick_beats_prologue_cel020, 4 },
    /* 006 */ { sick_beats_prologue_cel021, 56 },
    /* 007 */ END_ANIMATION,
};

struct Animation anim_sick_beats_prologue_unused[] = {
    /* 000 */ { sick_beats_prologue_cel000, 60 },
    /* 001 */ { sick_beats_prologue_cel007, 12 },
    /* 002 */ { sick_beats_prologue_cel008, 4 },
    /* 003 */ { sick_beats_prologue_cel009, 4 },
    /* 004 */ { sick_beats_prologue_cel010, 4 },
    /* 005 */ { sick_beats_prologue_cel011, 4 },
    /* 006 */ { sick_beats_prologue_cel012, 1 },
    /* 007 */ { sick_beats_prologue_cel013, 1 },
    /* 008 */ { sick_beats_prologue_cel014, 1 },
    /* 009 */ { sick_beats_prologue_cel015, 60 },
    /* 010 */ END_ANIMATION,
};

